# DX 704 Week 7 Project

This week's project will investigate issues in a quadcopter controller based using a linear quadratic regulator.
You will start with an existing model of the system and logs from a quadcopter based on it, investigate discrepancies, and ultimately train a new model of the system dynamics.

The full project description and a template notebook are available on GitHub: [Project 7 Materials](https://github.com/bu-cds-dx704/dx704-project-07).


## Example Code

You may find it helpful to refer to these GitHub repositories of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples
* https://github.com/bu-cds-omds/dx603-examples
* https://github.com/bu-cds-omds/dx704-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Introduction

You've just joined a drone startup.
On your first day, you join your new team to watch a test flight for a new quadcopter prototype.
Watching the prototype fly, the team comments that it is not as smooth as usual and suspects that something is off in the controller.
They provide you a copy of the dynamics model and log data from the prototype to investigate.

The quadcopter control model is a slightly more sophisticated version of the 1D quadcopter problem previously considered.

The state vector $\mathbf{x}_t$ now includes an acceleration component, and the action vector now has a servo control for the throttle instead of a raw force component.
\begin{array}{rcl}
\mathbf{x}_t & = & \begin{bmatrix} x_t \\ v_t \\ a_t \end{bmatrix} \\
\mathbf{u_t} & = & \begin{bmatrix} u_t \end{bmatrix}
\end{array}

## Part 1: Reconstruct the Control Matrix

You are provided the dynamics model in the files `model-A.tsv`, `model-B.tsv`, `cost-Q.tsv` and `cost-R.tsv`.
Recompute the control matrix $\mathbf{K}$ to be used in the infinite horizon linear quadratic regulator problem.

In [1]:
# YOUR CHANGES HERE

# imports
import pandas as pd
import numpy as np
import control

# load and align
A = pd.read_csv("model-A.tsv", sep="\t", index_col=0).to_numpy()
B = pd.read_csv("model-B.tsv", sep="\t", index_col=0).to_numpy()
Q = pd.read_csv("cost-Q.tsv", sep="\t", index_col=0).to_numpy()
R = pd.read_csv("cost-R.tsv", sep="\t", index_col=0).to_numpy()

# LQR time horizon
K, S, E = control.dlqr(A, B, Q, R)

# K
print("K")
print(K)



K
[[0.33445985 1.30445413 1.85813088]]


Save $\mathbf{K}$ in a file "control-K-intended.tsv" with columns x, v and a.

In [2]:
# YOUR CHANGES HERE

df_K = pd.DataFrame(K, columns=["x", "v", "a"])
df_K.to_csv("control-K-intended.tsv", sep="\t", index=False)

Submit "control-K-intended.tsv" in Gradescope.

## Part 2: Recompute the Actions for the Logged States

You get access to the log data for the prototype as the file "qc-log.tsv".
It conveniently saves all the state and actions made.
Recompute the actions based on your $\mathbf{K}$ matrix computed in part 1.

In [3]:
# YOUR CHANGES HERE

# log to df
log_df = pd.read_csv("qc-log.tsv", sep="\t")

# K matrix
K_df = pd.read_csv("control-K-intended.tsv", sep="\t")
K = K_df.values   

# state vectors
X = log_df[["x", "v", "a"]].values   

# compute
computed = -(X @ K.T).flatten()

# output to df
output = pd.DataFrame({
    "index": log_df["index"],
    "u_check": computed
})



Save your computed actions as "qc-check.tsv" with columns "index" and "u_check".

In [4]:
# YOUR CHANGES HERE

# save file
output.to_csv("qc-check.tsv", sep="\t", index=False)

Submit "qc-check.tsv" in Gradescope.

## Part 3: Reverse Engineer the Actual Control Matrix

Now that you have found a systematic difference between your computed actions and the logged actions, estimate $
$, the control matrix that was actually used to choose actions in the prototype.

Hint: With a linear quadratic regulator, the optimal actions are always linear combinations of the state that are calculated using the control matrix.
You can use linear regression to reverse-engineer the coefficients in the control matrix.

In [5]:
# YOUR CHANGES HERE

# linear regr
from sklearn.linear_model import LinearRegression

# log_df for predictors
X = log_df[["x", "v", "a"]].values

# target u values 
y = log_df["u"].values

# fit linear
model = LinearRegression(fit_intercept=False)
model.fit(X, y)

# K actual
K_actual = -model.coef_.reshape(1, -1)

print("K_actual")
print(K_actual)

K_actual
[[0.34043755 1.30012023 1.95011696]]


Save $\mathbf{K}_{\mathrm{actual}}$ in "control-K-actual.tsv" with the same format as "control-K-intended.tsv".

In [6]:
# YOUR CHANGES HERE

df_K_actual = pd.DataFrame(K_actual, columns=["x", "v", "a"])
df_K_actual.to_csv("control-K-actual.tsv", sep="\t", index=False)

Submit "control-k-actual.tsv" in Gradescope.

## Part 4: Recompute the System Dynamics from the Log Data

On further investigation, it turns out that the control matrix $\mathbf{K}$ in the prototype was modified to compensate for state prediction errors.
You would like to recompute the $\mathbf{A}$ and $\mathbf{B}$ matrices using the log data since they are used to predict the next states.
However, since the action vector $\mathbf{u}_t$ is linearly dependent on the state via $\mathbf{u}_t=-\mathbf{K} \mathbf{x}_t$, you need a new data set so you can separate the effects of the $\mathbf{A}$ and $\mathbf{B}$ matrices.
Your co-workers kindly provide a new file "qc-train.tsv" where noise was added to each action.
Estimate the true $\mathbf{A}$ and $\mathbf{B}$ matrices based on this file.

In [7]:
# YOUR CHANGES HERE

# training 
train_df = pd.read_csv("qc-train.tsv", sep="\t")

# state/action at t
X_t = train_df[["x", "v", "a", "u"]].iloc[:-1].values

# state at time t+1
Y_tp1 = train_df[["x", "v", "a"]].iloc[1:].values

# fit x_(t+1) = A x_t + B u_t
model = LinearRegression(fit_intercept=False)
model.fit(X_t, Y_tp1)

# coef matrix
coef = model.coef_

# new
A_new = coef[:, :3]
B_new = coef[:, 3:].reshape(3, 1)

# sanity
print("A_new")
print(A_new)
print()
print("B_new")
print(B_new)

A_new
[[ 1.00000000e+00  1.10000000e+00  2.88657986e-15]
 [-1.28195498e-16  9.00000000e-01  9.50000000e-01]
 [-9.31378031e-17  5.55111512e-16  1.10000000e+00]]

B_new
[[-1.11022302e-16]
 [-1.00000000e-02]
 [ 9.00000000e-01]]


In [8]:
# save A
df_A_new = pd.DataFrame(
    A_new,
    columns=["x", "v", "a"],
    index=["x", "v", "a"]
)

# save B
df_B_new = pd.DataFrame(
    B_new,
    columns=["u"],
    index=["x", "v", "a"]
)

Save $\mathbf{A}$ and $\mathbf{B}$ to "model-A-new.tsv" and "model-B-new.tsv" respectively.

In [9]:
# YOUR CHANGES HERE
df_A_new.index.name = "index"
df_A_new.to_csv("model-A-new.tsv", sep="\t")

df_B_new.index.name = "index"
df_B_new.to_csv("model-B-new.tsv", sep="\t")

Submit "model-A-new.tsv" and "model-B-new.tsv" in Gradescope.

## Part 5: Code

Please submit a Jupyter notebook that can reproduce all your calculations and recreate the previously submitted files.
You do not need to provide code for data collection if you did that by manually.

## Part 6: Acknowledgements

If you discussed this assignment with anyone, please acknowledge them here.
If you did this assignment completely on your own, simply write none below.

If you used any libraries not mentioned in this module's content, please list them with a brief explanation what you used them for. If you did not use any other libraries, simply write none below.

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the generative AI policy. If you did not use any generative AI tools, simply write none below.